runtime: python310

entrypoint: uvicorn backend.main:app --host=0.0.0.0 --port=$PORT

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "backend/finsight-agentic-ai-ac0ca32723f8.json"

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
